<a href="https://colab.research.google.com/github/VitaliyRepko/Machine-Learning/blob/main/%D0%9B%D0%A01_%D0%9C%D0%9D_%D0%A0%D0%B5%D0%BF%D0%BA%D0%BE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

На парі був присутній. Репко В.А. 4-8 ФІТ

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
mtrx = np.random.randint(1, 6, size=(3, 3))
mtrx

array([[3, 1, 1],
       [5, 2, 5],
       [1, 5, 5]])

In [ ]:
det = np.linalg.det(mtrx)
det

np.float64(-42.00000000000001)

In [ ]:
product = np.prod(mtrx)
product

np.int64(3750)

In [ ]:
product_1 = np.prod(mtrx[0])
product_2 = np.prod(mtrx[1])
product_3 = np.prod(mtrx[2])
product_1 * product_2 * product_3

np.int64(3750)

In [ ]:
sum_mtrx = np.sum(mtrx)
sum_mtrx

np.int64(28)

In [ ]:
max_elem = np.max(mtrx)
min_elem = np.min(mtrx)
print("Найбільший елемент матриці:", max_elem)
print("Найменший елемент матриці:", min_elem)

Найбільший елемент матриці: 5
Найменший елемент матриці: 1


In [ ]:
np.mean(mtrx)

np.float64(3.111111111111111)

In [ ]:
np.sqrt(mtrx)

array([[1.73205081, 1.        , 1.        ],
       [2.23606798, 1.41421356, 2.23606798],
       [1.        , 2.23606798, 2.23606798]])

In [ ]:
np.sum(mtrx, axis=1).reshape(-1, 1)

array([[ 5],
       [12],
       [11]])

In [ ]:
vector = np.random.randint(0, 10, size=25)
vector

array([5, 6, 8, 6, 5, 3, 6, 2, 5, 2, 5, 4, 6, 9, 8, 0, 3, 4, 2, 0, 0, 2,
       0, 3, 9])

In [ ]:
np.sort(vector)[::-1]

array([9, 9, 8, 8, 6, 6, 6, 6, 5, 5, 5, 5, 4, 4, 3, 3, 3, 2, 2, 2, 2, 0,
       0, 0, 0])

In [ ]:
from scipy import stats
stats.mode(vector)

ModeResult(mode=np.int64(0), count=np.int64(4))

In [ ]:
np.median(vector)

np.float64(4.0)

In [ ]:
np.mean(vector)

np.float64(4.12)

In [ ]:
np.max(vector)

np.int64(9)

In [ ]:
np.min(vector)

np.int64(0)

In [ ]:
mtrx1 = np.random.randint(1, 11, size=(4, 4))
mtrx2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(mtrx1)

print("Матриця 2:")
print(mtrx2)

Матриця 1:
[[ 9  5  3  3]
 [ 6  4  5  9]
 [ 5  4  6  5]
 [ 9  4  5 10]]
Матриця 2:
[[ 2  9  2  4]
 [ 5  4  2  2]
 [10  6  7  1]
 [ 3 10  6  4]]


In [ ]:
mtrx1 + mtrx2

array([[11, 14,  5,  7],
       [11,  8,  7, 11],
       [15, 10, 13,  6],
       [12, 14, 11, 14]])

In [ ]:
mtrx1 - mtrx2

array([[ 7, -4,  1, -1],
       [ 1,  0,  3,  7],
       [-5, -2, -1,  4],
       [ 6, -6, -1,  6]])

In [ ]:
mtrx1 * mtrx2

array([[18, 45,  6, 12],
       [30, 16, 10, 18],
       [50, 24, 42,  5],
       [27, 40, 30, 40]])

In [ ]:
np.divide(mtrx1, mtrx2, where=(mtrx2!=0))

array([[4.5       , 0.55555556, 1.5       , 0.75      ],
       [1.2       , 1.        , 2.5       , 4.5       ],
       [0.5       , 0.66666667, 0.85714286, 5.        ],
       [3.        , 0.4       , 0.83333333, 2.5       ]])

In [ ]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [ ]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [ ]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

In [ ]:
x1 = np.arange(6)
x2 = np.array([1, 3, 5, 4, 2, 4])
x1 ** x2

array([  0,   1,  32,  81,  16, 625])

In [ ]:
vec = np.array([1, 2, 3, 4, 5])
vec

array([1, 2, 3, 4, 5])

In [ ]:
vec = np.matrix([1, 2, 3, 4, 5])
vec.T

matrix([[1],
        [2],
        [3],
        [4],
        [5]])

In [ ]:
vec = np.array([1, 2, 3, 4, 5])
vec[::-1]

array([5, 4, 3, 2, 1])

In [ ]:
newvec = np.flip(vec)
print(newvec)

[5 4 3 2 1]


In [ ]:
print(np.mean(newvec))

3.0


In [ ]:
np.max(newvec)

np.int64(5)

In [ ]:
np.min(newvec)

np.int64(1)

In [ ]:
v1 = np.array([3, 4, 1])
v1

array([3, 4, 1])

In [ ]:
v2 = np.array([6, 2, 4])
v2

array([6, 2, 4])

In [ ]:
np.dot(v1, v2)

np.int64(30)

In [ ]:
vec = np.array([1, 2, 3, 4, 5])
normal = np.linalg.norm(vec)

print(normal)
vec/normal

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

In [ ]:
vec1 = np.array([1, 0, 0])
vec2 = np.array([0, 1, 0])

np.dot(vec1, vec2)
#Вектори ортогональні

np.int64(0)

In [ ]:
vec = np.array([1, 2, 5, 2, 4, 7, 1, 7, 2, 4])
np.unique(vec)

array([1, 2, 4, 5, 7])

In [ ]:
vec = np.array([1, 2, 3, 4, 5])
length = np.linalg.norm(vec)

length

np.float64(7.416198487095663)

In [ ]:
np.isclose(length, 5)
#Не дорівнює

np.False_

In [ ]:
mtrx = np.random.randint(0, 11, (3,3))
mtrx

array([[5, 5, 8],
       [3, 2, 3],
       [8, 5, 5]])

In [ ]:
np.linalg.det(mtrx)

np.float64(11.99999999999999)

In [ ]:
np.linalg.inv(mtrx)

array([[-0.41666667,  1.25      , -0.08333333],
       [ 0.75      , -3.25      ,  0.75      ],
       [-0.08333333,  1.25      , -0.41666667]])

In [ ]:
a = np.array([[1, 3, -5], [0, -2, 5], [-1, 5, 2]])
b = np.array([3, 2, 2])

x = np.linalg.solve(a, b)
print("Вбудована функція: ", x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print("Матричний метод:", x1)

Вбудована функція:  [4.08823529 0.91176471 0.76470588]
Матричний метод: [4.08823529 0.91176471 0.76470588]
